version: '3'
services:
  app:
    volumes:
      - ./:/var/phpapp/
    build:
      context: ./docker/php-fpm

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/phpapp/
  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    volumes:
      - ./testdata/:/data
    environment:
        MYSQL_DATABASE: app
        MYSQL_ROOT_PASSWORD: root
